version: '3'

services:
  postgres_prod:
    image: 'postgres:14'
    privileged: true
    user: root
    container_name: 'postgres-db-production'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=database'
      -  'PGDATA=/var/lib/postgresql/data/pgdata'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./db_production:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres



  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:5.7
    privileged: true
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres



  app:
    image: 'userauthmanagementback:latest'
    privileged: true
    user: root
    container_name: 'backend-app-production'
    ports:
      - 80:8080
    environment:
      - 'POSTGRES_URL=jdbc:postgresql://postgres-db-production:5432/productionDb?useSSL=false'
    volumes:
      - ./Upload_prod:/Upload
    networks:
      - postgres

networks:
  postgres:
    driver: bridge